<?php

include_once('kr_2012.features.inc');

function kr_2012_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => 'Byer i Norge', 
    );
    $blocks[1] = array(
      'info' => 'Ordforerleksikon', 
    );
    $blocks[2] = array(
      'info' => 'Norskeradmenn', 
    );
    return $blocks;
  }
  else if ($op == 'configure') {
  	
  	$form['tittel'] = array(
  	  '#type' => 'textfield',
  	  '#title' => 'Tittel',
  	  '#default_value' => variable_get('kr_2012_tittel_'.$delta, ''),
	);
  	$form['link'] = array(
  	  '#type' => 'textfield',
  	  '#title' => 'Link',
  	  '#default_value' => variable_get('kr_2012_link_'.$delta, ''),
	);
    $form['text'] = array(
      '#type' => 'textarea', 
      '#title' => t('Text'), 
      '#default_value' => variable_get('kr_2012_text_'.$delta, ''), 
    );
    return $form;
  }
  else if ($op == 'save') {
    variable_set('kr_2012_text_'.$delta, $edit['text']);
	variable_set('kr_2012_tittel_'.$delta, $edit['tittel']);
	variable_set('kr_2012_link_'.$delta, $edit['link']);
  }
  else if ($op == 'view') {
  	$block = array(
		'subject' => l(variable_get('kr_2012_tittel_'.$delta, ''), variable_get('kr_2012_link_'.$delta, '')),
		'content' => _kr_2012_block_content($delta)
	);

    return $block;
  }
}
function _kr_2012_block_content($delta){
	$html = '<a href="'.url(variable_get('kr_2012_link_'.$delta, '')).'" class="link">Link</a>';
	$html .= '<div class="desc">'.variable_get('kr_2012_text_'.$delta, '').'</div>';
	return $html;
}

function kr_2012_pathauto_alias_alter(&$alias, $context) {
	$alias = str_replace('wbr', '', $alias);
	$alias = str_replace('&hyphen;', '', $alias);
	$alias = str_replace('hyphen', '', $alias);
	$alias = str_replace('173', '', $alias);
	//&#173;
	
}
function kr_2012_form_alter(&$form, &$form_state, $form_id){
	if($form_id == 'article_node_form'){
		$theme = variable_get('theme_default', '');
		if($theme == 'kr2012'){
			$form['title']['#description'] .= 'Legg inn '.htmlentities('#').' for å bryte ord, om de ikke får plass på en linje.';
		}
	}
}

function kr_2012_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){
	switch ($op) {
    	case 'presave':
			$pattern = '/(?<!\&)\\#/';
			$replacement = '&#173;';
			$ny_tittel = preg_replace($pattern, $replacement, $node->title);
			$node->title = $ny_tittel;
			break;
		case 'prepare':
			$pattern = '/&#173;/';
			$replacement = '#';
			$ny_tittel = preg_replace($pattern, $replacement, $node->title);
			$node->title = $ny_tittel;
			
			break;
	}
}
