<?php

include_once('kr_2012.features.inc');

function kr_2012_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => 'Byer i Norge', 
    );
    $blocks[1] = array(
      'info' => 'Ordforerleksikon', 
    );
    $blocks[2] = array(
      'info' => 'Norskeradmenn', 
    );
    return $blocks;
  }
  else if ($op == 'configure') {
  	
  	$form['title'] = array(
  	  '#type' => 'textfield',
  	  '#title' => 'Tittel',
  	  '#default_value' => variable_get('kr_2012_tittel_'.$delta, ''),
	);
  	$form['link'] = array(
  	  '#type' => 'textfield',
  	  '#title' => 'Link',
  	  '#default_value' => variable_get('kr_2012_link_'.$delta, ''),
	);
    $form['text'] = array(
      '#type' => 'textarea', 
      '#title' => t('Text'), 
      '#default_value' => variable_get('kr_2012_text_'.$delta, ''), 
    );
    return $form;
  }
  else if ($op == 'save') {
    variable_set('kr_2012_text_'.$delta, $edit['text']);
	variable_set('kr_2012_title_'.$delta, $edit['title']);
	variable_set('kr_2012_link_'.$delta, $edit['title']);
  }
  else if ($op == 'view') {
  	$block = array(
		'subject' => variable_get('kr_2012_tittel_'.$delta, ''),
		'content' => _kr_2012_block_content($delta)
	);

    return $block;
  }
}
function _kr_2012_block_content($delta){
	$html = '<a href="'.url(variable_get('kr_2012_link_'.$delta, '')).'" class="link"></a>';
	$html .= '<div>'.variable_get('kr_2012_text_'.$delta, '').'</div>';
	return $html;
}
