<?php

include_once('tema.features.inc');

function tema_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
  	$blocks = array();
	$result = db_query_range('SELECT n.nid, n.title, n.created
    FROM {node} n WHERE n.type LIKE \'tema\' ORDER by n.created DESC', $uid, 0, 10);
  	while ($node = db_fetch_object($result)) {
  		$blocks[$node->nid] = array(
			'info' => $node->title,
			'cache' => BLOCK_CACHE_PER_PAGE,
		);
  	}
	
	return $blocks;
  }
  else if ($op == 'configure') {
  	/*
  	$options = array('std' => '1-3 | En toppsak tre undersaker');
    $form['layout'] = array(
      '#type' => 'select', 
      '#title' => t('Layout'), 
      '#default_value' => variable_get('tema_layout_'.$delta, 'std'), 
      '#options' => $options,
    );
    return $form;
	*/
  }
  else if ($op == 'save') {
  	/*
    variable_set('tema_layout_'.$delta, $edit['layout']);
	cache_clear_all('tema_block_'.$delta);
	 */
  }
  else if ($op == 'view') {
  	drupal_add_css(drupal_get_path('module', 'tema') .'/tema.css');
	$block = _tema_block($delta);
	return $block;
  }
}

function _tema_block($nid){
	$cache = cache_get('tema_block_'.$nid);
	
	if (is_array($cache->data)) {
	  	$data = $cache->data;
	}
	else {
		
		$node = node_load($nid);
		$layout = variable_get('tema_layout_'.$nid, 'std');
		//$content = '<div class="edit-tema-link">'.l('Rediger block', 'admin/build/block/configure/tema/'.$nid).'</div>';
		if($layout == 'std'){
			$content .= _tema_layout_std($node);
		}
		$data = array(
	  		'subject' => '<div class="tema-title">'.l($node->title, 'node/'.$node->nid).'</div>', 
	  		'content' => $content,
	  		'node_id' => $nid,
	  		'layout' =>  $layout,
		);
		cache_set('tema_block_'.$nid, $data, (time()+3600));
	}
  
  return $data;
}
function _tema_layout_std($node){
	
	$saker = $node->field_tema_saker;
	$show = $node->field_tema_vis_pa_forsiden;
	$show_nodes = 0;
	foreach($show as $delta => $value){
		if($value['value'] == 1){
			$show_nodes++;
		}
		
	}	
	if(count($show_nodes)>0){
		$number = 1;		
		foreach ($saker as $delta => $item) {
			if($show[$delta]['value'] == 1){
				$sub_nid = $item['nid'];
				$sub_node = node_load($sub_nid);
				if($number == 1){				
					$bilde = $sub_node->field_main_image[0]['filename']; //filepath
					$content.= '<div class="item first number-'.$number.'">';
					if(isset($sub_node->field_main_image[0]['fid'])){
						$content.= '<div class="image"><a href="'.url('node/'.$sub_nid).'">'. theme('imagecache', 'tema_1_3_stor', $bilde).'</a></div>';
					}
					$content.= '<div class="node-title"><h2>'.l($sub_node->title, 'node/'.$sub_node->nid).'</h2></div>';
					if(strlen($sub_node->field_teaser[0]['value'])>2){
						$content.= '<div class="node-text"><p>'.check_plain($sub_node->field_teaser[0]['value']).'</p></div>';
					}
					$content.= '</div>';
				}
				else{
					$bilde = $sub_node->field_main_image[0]['filename']; //filepath
					$css_class = 'item number-'.$number;
					if($number == $show_nodes){
						$css_class .= ' last';
					}
					$content.= '<div class="'.$css_class.'">';
					if(isset($sub_node->field_main_image[0]['fid'])){
						$content.= '<div class="image"><a href="'.url('node/'.$sub_nid).'">'.theme('imagecache', 'tema_liten', $bilde).'</a></div>';
					}
					$content.= '<div class="node-title"><h2>'.l($sub_node->title, 'node/'.$sub_node->nid).'</h2></div>';
					if(strlen($sub_node->field_teaser[0]['value'])>2){
						$content.= '<div class="node-text"><p>'.check_plain($sub_node->field_teaser[0]['value']).'</p></div>';
					}
					$content.= '</div>';
				}

				$number++;
			}
		}
	}
	return $content;
}
