<?php

/*
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function kr_import_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

function kr_import_xlat_node($nid) {
	return 'haha';
}

function kr_import_menu () {
	$items['onode/%'] = array(
    'title' => 'Old article', 
    'page callback' => 'kr_import_old_article_callback',
    'page arguments' => array(1), 
    'access arguments' => array('access content'), 
    'type' => MENU_CALLBACK,
  );
	
	return $items;
}

function kr_import_old_article_callback ($sourceid) {
	$method = 'Articles';
	print($sourceid1);
	$map_table = 'migrate_map_' . strtolower($method);
	
	if ($destid1 = $migrate_map = db_result(db_query("SELECT mt.destid1 FROM $map_table mt LEFT JOIN kr_import_articles ka ON ka.krid = mt.sourceid1 WHERE ka.objid = %d", $sourceid))) {
  	// Hurray. We already migrated this content. Go there.
  	watchdog('KR Import', 'Old article id loaded. ID: !id', array('!id'=>$sourceid));
		drupal_goto(kr_import_migrate_build_url($destid1, $method), null, null, 301);
	}
	
	drupal_set_message(variable_get('kr_no_source_msg', 'Kommunal Rapport har fått ny publiseringsløsning. Ikke alle gamle linker fungerer. Du er nå videresendt til vår forside.'));

	drupal_goto('', null, null, 301);
	return 'Source does not exist.';
}

function kr_import_migrate_build_url($destid1, $migration_name) {
  global $base_url;

  // TODO: Add an entry for each migration that we need to redirect.
  $patterns = variable_get('migrate_patterns', array(
    'Articles' => 'node/:source_id',
  ));
  $pattern = $patterns[$migration_name];

  // Swap in the destination ID.
  $destination_uri = str_replace(':source_id', $destid1, $pattern);

  // For speed, we go right to aliases table rather than more bootstrapping.
  if ($uri_clean = db_result(db_query("SELECT alias FROM {url_alias} WHERE source = '%s'", $destination_uri))) {
    $destination_uri = $uri_clean;
  }

  // Build absolute url for 301 redirect.
  return  $base_url . '/' . $destination_uri;
}