<?php

include_once('statistics_node.features.inc');
require_once('lib/parsecsv.lib.php');

function statistics_node_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'view':
			//dpm($node);
			if($node->type == 'chart') {
				unset($node->content['field_values']);
			
      	$node->content['chart_output'] = array(
        	'#value' => _statistics_node_generate_chart($node), 
        	'#weight' => 10,
      	);	
			} else if($node->type == 'table') {
				unset($node->content['field_values']);
			
      	$node->content['chart_output'] = array(
        	'#value' => _statistics_node_generate_table($node->field_values[0]['value']), 
        	'#weight' => 10,
      	);	
			}
			
      break;
  }
}

function _statistics_node_generate_chart ($node) {
	// Define chart type
	// Define
	$values = $node->field_values[0]['value'];
	$data_array = _statistics_node_parse_chart_values($values);
	
	$chart_data = array(
		'#plugin'    => 'jqplot', // Google Charts API will be used
  	'#type'     => 'line2D', // To show a simple 2D line chart
  	'#color'    => '336699', // background color, in RRGGBB format
  	'#title'	  => $node->title,
	);
	
	foreach($data_array as $data) {
		$chart_data[] = $data;
	}
	
	return charts_chart($chart_data);
}

function _statistics_node_parse_chart_values($values) {
	$csv = new parseCSV();
	$csv->heading = false;
	$csv->delimiter = ';';
	$csv->parse($values);
	
	$data = array();
	
	foreach(array_shift($csv->data) as $key => $legend) {
		$data[$key] = array('#legend'=>$legend);
	}
	
	foreach($csv->data as $row) {
		foreach ($row as $key=>$val) {
			$data[$key][] = (int)$val;
		}
	}
	
	return $data;
}

function _statistics_node_generate_table ($values) {
	_statistics_node_init_table ();
	$values_array = _statistics_node_parse_table_values($values);
	return theme('table', array_shift($values_array), $values_array, array('class'=>'data-table'));
}

function _statistics_node_parse_table_values($values) {	
	$csv = new parseCSV();
	$csv->heading = false;
	$csv->parse($values);

	return $csv->data;
}

function _statistics_node_init_table () {
	$path = drupal_get_path('module', 'statistics_node');
	drupal_add_js($path.'/js/statisticsTable.js');
	drupal_add_js($path.'/datatables/media/js/jquery.dataTables.js');
	drupal_add_css($path.'/datatables/media/css/demo_table.css');
	drupal_add_css($path.'/statistics_node_table.css');
}
