<?php

function subscriber_status_form_user_profile_form_alter(&$form, $form_state) {
    //print_r($form_state);
    //print_r($form);
    if (isset($form['Abonnementsinfo'])) {
        /*
         * [3] => administrator
         * [8] => premium
         * [9] => ip abonnent
         * [10] => gratisleser
         * [11] => abonnent
         * [12] => free
         * [13] => disabled
         */

        $value = $GLOBALS['user']->roles;
        unset($value[2]);
        $value = implode(", ", $value);

        $form['Abonnementsinfotest']['profile_subscriber_status'] = array(
             '#type' => 'fieldset',
             '#title' => t('Status på ditt abonnement'),
             '#description' => t('Viser status på ditt abonnement på kommunal-rapport.no.'),
             '#disabled' => true,
             '#weight' => 0,
             '#value' => $value
            );
    }
}