<?php

function kr_diverse_block($op = 'list', $delta = 0, $edit = array()) {

  if ($op == 'list') {
    $blocks[0] = array(
      'info' => 'KR: addthis widget', 
      'cache' => BLOCK_CACHE_PER_PAGE,
    );
    return $blocks;
  }

  else if ($op == 'view') {
    switch ($delta) {
      case 0:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => '', 
          'content' => _kr_div_addthis(),
        );
        break;
    }
    return $block;
  }
}

function _kr_div_addthis(){
  if(arg(2) == 'edit' || arg(1) =='add'){
    return;
  }
  $node=node_load(arg(1));
  $addthis_link_title=$node->title;
  return theme('op_addthis_widget', $addthis_link_title);
}

function kr_diverse_form_alter(&$form, &$form_state, $form_id) {
print $form_id . '<br>';
  if($form_id == 'article_node_form' && arg(1)=='add'){
    
    global $user;
    $query = db_query('SELECT nr.title, n.nid FROM {content_type_author} ca
    LEFT JOIN {node} n ON ca.nid=n.nid
    LEFT JOIN {node_revisions} nr ON nr.vid=n.vid
    WHERE ca.field_author_user_uid LIKE %d',$user->uid);
    $result = db_fetch_object($query);

 // drupal_set_message($form_id.' '.$result->title);
    if($result->nid>0){
      $js='
      Drupal.behaviors.kr_div = function (context) {
        $("#edit-field-op-author-0-nid-nid").val("'.$result->title.' [nid:'.$result->nid.']");
      };
      ';
  //drupal_set_message($js);
      drupal_add_js($js, 'inline');
    }
  }

  //$("#edit-field-op-author-0-nid-nid").value(22);
}
function kr_diverse_nodeapi(&$node, $op, $teaser, $page) {
  switch ($op) {
    case 'insert':
    case 'update':
    case 'delete':
    case 'delete revision':
      //views_content_cache_update_set($node, 'node');
      if(function_exists('expire_cache_derivative')){
        $paths['front'] = '<front>';
        expire_cache_derivative($paths);
      }
      
      break;
  }
  if($op == 'view' && $node->type =='job'){
    $node->title = str_replace('_', '',$node->title);  
    $node->content['#title'] = str_replace('_', '',$node->title);  
    drupal_set_title(str_replace('_', '',$node->title));
  }
}

/**
 * Implementation of hook_twitter_pull_blocks()
 */
function kr_diverse_twitter_pull_blocks() {
  $block->delta = 'kr_tweets';
  $block->name = t('KR Tweets');
  $block->title = t('Kommunevalg på Twitter');
  $block->tweetkey = 'kommunevalg';
  $block->number_of_items = 7;
//  $block->theme_key = 'kr_tweets';
  return array($block->delta => $block);
}