<?php

/**
 * @author Gerd Riesselmann
 * @author Jeff Warrington (jaydub) is new maintainer March 2008
 * @author Chris Nutting <Chris.Nutting@openx.org>
 * @author Bruno Massa
 *
 * @file
 * Integrates Drupal with OpenX Ad server
 */

/**
 * Implementation of hook_block().
 */
function openx_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $zones = variable_get('openx_zones', array());
    foreach ($zones as $index => $zone) {
      if ($zone['id']) {
        $blocks[$index] = array(
          'info'    => t('OpenX Zone !id (!name)', array('!id' => $zone['id'], '!name' => (empty($zone['name']) ? t('untitled') : $zone['name']))),
          'weight'  => 0,
          'enabled' => 0,
          'region'  => 'left',
          'cache'   => BLOCK_NO_CACHE
        );
      }
    }
    return $blocks;
  }
  elseif ($op == 'view') {
    $block = array(
      'content' => openx_invoke($delta)
    );
    return $block;
  }
}

/**
 * Implementation of hook_help().
 */
function openx_help($section, $arg = NULL) {
  switch ($section) {
    case 'admin/help#openx':
    case 'admin/modules#description':
      return '<p>'. t('The OpenX module allows site administrators to integrate Drupal with the OpenX adserver.
        OpenX ad zones that are configured to be used in with openx module can be shown anywhere
        in a theme directly using a function call or via Drupal blocks which are automatically
        created for each OpenX ad zone. Additional information regarding OpenX can be found at the
        <a href="http://www.openx.org">OpenX website</a>.') .'</p>';
  }
}

/**
 * Implementation of hook_menu().
 */
function openx_menu() {
  $items['admin/settings/openx'] = array(
    'access arguments'  => array('administer site configuration'),
    'description'       => 'Configure OpenX AdServer integration behavior and appearance.',
    'file'              => 'openx.admin.inc',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('_openx_settings'),
    'title'             => 'OpenX',
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function openx_theme() {
  return array(
    'openx_settings_zones' => array(
      'arguments' => array('form' => array()),
      'file' => 'openx.admin.inc',
    ),
    'openx_site_vars' => array(
      'arguments' => array('form' => array()),
      'file' => 'openx.admin.inc',
    ),
  );
}

/**
 * Builds the call to OpenX
 *
 * @param $index_or_key
 *   Number or String. The zone ID number or the it's 'nickname'
 * @return
 *   HTML. The area where the banner will be displayed
 */
function openx_invoke($index_or_key) {
  module_load_include('inc', 'openx');
  if (!$zone = _openx_get_zone($index_or_key)) {
    return '';
  }

  // Add the JS on top of the page
  _openx_javascript();

  return "<script type='text/javascript'><!--// <![CDATA[
    OA_show('{$zone['name']}');
// ]]> --></script>";
}
