<?php

function google_cron_fetcher_cron(){
  gc_global_visits();
  gc_daily_visits();
}

function gc_daily_visits(){
  $cache_options = array(
	  'cid' => 'google_analytics_counter_' . md5(time()),
	  'expire' => google_analytics_reports_cache_time(),
	  'refresh' => FALSE,
  );
  
  $params = array(
    'profile_id' => 'ga:' . variable_get('google_analytics_reports_profile_id', 0),
    'metrics' => array('ga:pageviews'),
    'dimensions' => array('ga:pagePath'),
    'max_results' => 5000,
    'sort' => array('ga:pagePath'),
    'start_index' => 1,
    'start_date' => strtotime('today'),
    'end_date' => strtotime('today'),
  );
  $GAFeed = google_analytics_api_new_gafeed();
  
  $GAFeed->queryReportFeed($params, $cache_options);  
  if(count($GAFeed->results) > 0){
    $i = 0;
	$ni= 0;
    foreach ($GAFeed->results as $delta => $item) {
      $i++;
      $views = $item['pageviews'];
      $nid = google_path_to_nid($item['pagePath']);
      if($nid){
      	$ni++;
        db_query('UPDATE {node_counter} SET daycount = %d WHERE timestamp = %d AND nid = %d', $views, strtotime('today'), $nid);
        // If we affected 0 rows, this is the first time viewing the node.
        if (!db_affected_rows()) {
          // We must create a new row to store counters for the new node.
          db_query('INSERT INTO {node_counter} (nid, daycount, totalcount, timestamp) VALUES (%d, %d, %d)', $nid, $views, $views, strtotime('today'));
        }        
      }
    }

  }

}

function gc_global_visits(){
  $cache_options = array(
  'cid' => 'google_analytics_counter_' . md5(time()),
  'expire' => google_analytics_reports_cache_time(),
  'refresh' => FALSE,
  );
  
  $index = variable_get('google_cron_fetcher_index', 1);
  $params = array(
    'profile_id' => 'ga:' . variable_get('google_analytics_reports_profile_id', 0),
    'metrics' => array('ga:pageviews'),
    'dimensions' => array('ga:pagePath'),
    'max_results' => 5000,
    'filters' => 'ga:pagePath=~^/artikkel.*',
    'sort' => array('ga:pagePath'),
    'start_index' => $index,
    'start_date' => strtotime('1 January 2005'),
    'end_date' => strtotime('today'),
  );
  
  
  $GAFeed = google_analytics_api_new_gafeed();
  $GAFeed->queryReportFeed($params, $cache_options);
  if(count($GAFeed->results) > 0){
    $i = 0;
	$ni = 0;
    foreach ($GAFeed->results as $delta => $item) {
      $i++;
      $views = $item['pageviews'];
      $nid = google_path_to_nid($item['pagePath']);
      if($nid){
      	$ni++;
        db_query('UPDATE {node_counter} SET totalcount = %d WHERE timestamp = %d AND nid = %d', $views, strtotime('today'), $nid);
        // If we affected 0 rows, this is the first time viewing the node.
        if (!db_affected_rows()) {
          // We must create a new row to store counters for the new node.
          db_query('INSERT INTO {node_counter} (nid, daycount, totalcount, timestamp) VALUES (%d, 0, %d, %d)', $nid, $views, strtotime('today'));
        }
      }
    }

    variable_set('google_cron_fetcher_index', $index+$i);
  }else{
    variable_set('google_cron_fetcher_index', 1);
  }
}
function google_path_to_nid($path){
  $path = substr($path, 1);
  $normal = drupal_get_normal_path($path);
  if($path == $normal){
    return 0;
  }else{
    $items = explode('/',$normal);
    return $items[1];
  }
}
?>