<?php

function google_cron_fetcher_cron(){

}

function global_visits(){
  $cache_options = array(
  'cid' => 'google_analytics_counter_' . md5(time()),
  'expire' => google_analytics_reports_cache_time(),
  'refresh' => FALSE,
  );
  
  $index = 1;
  $params = array(
    'profile_id' => 'ga:' . variable_get('google_analytics_reports_profile_id', 0),
    'metrics' => array('ga:pageviews'),
    'dimensions' => array('ga:pagePath'),
    'max_results' => 50,
    'sort' => array('-ga:pageviews'),
    'start-index' => $index,
  );
  
  
  $GAFeed = google_analytics_api_new_gafeed();
  $GAFeed->queryReportFeed($params, $cache_options);
  foreach ($GAFeed->results as $item) {
    $views = $item['pageviews'];
    $nid = google_path_to_nid($pagePath);
    if($nid){
      dsm($nid, $views);
    }
  }
}
function google_path_to_nid($path){
  $path = substr($path, 1);
  $normal = drupal_get_normal_path($path);
  if($path == $normal){
    return 0;
  }else{
    $items = explode('/',$normal);
    return $items[1];
  }
}
?>