<?php

// Drupal needs this blank file.

function utgivelser_form_alter(&$form, &$form_state, $form_id){
	if($form_id == 'taxonomy_form_term' && $form['#vocabulary']['name'] == 'Utgave'){
		unset($form['identification']['description']);
		if(!$form['#term']['tid']){
			$form['identification']['name']['#default_value'] = 'auto title';
			$form['identification']['name']['#description'] = 'Står det auto title vil systemet selv sette en utgavetittel';
		} 
		$form['fields']['#collapsed'] = FALSE;
		$form['#validate'][] = 'utgivelser_taxonomy_validate';
	}elseif($form_id == 'article_node_form'){
		$form['#after_build'][] = '_utgivelser_article_js';	
	}elseif($form_id == 'views_exposed_form'){
		if(strlen($form_state['input']['changed']['min']) == 0 && $form_state['input']['changed']['max'] == 0){
			$form_state['input']['changed']['min'] = date('d.m.Y', strtotime('-3 month'));
			$form_state['input']['changed']['max'] = date('d.m.Y');
		}
	}
	
}
function _utgivelser_article_js($element){
	drupal_add_js(drupal_get_path('module', 'utgivelser') . '/js/article.js');
	return($element);
}
function utgivelser_taxonomy_validate($form, &$form_state){
	if($form_state['values']['name'] == 'auto title'){
		$dato = $form_state['values']['fields']['utgivelsesdato']['value'];
		$year = substr($dato, 0, 4);		
		$q = db_query("SELECT COUNT(tid) as antall FROM term_fields_term
		WHERE utgivelsesdato_value LIKE '".$year."%'");
		$r = db_fetch_object($q);
		$form_state['values']['name'] = 'Nr '.($r->antall+1).'/'.$year;
	}
}
function utgivelser_views_query_alter(&$view, &$query){
	if($view->name == 'admin_content'){
		foreach($query->where[0]['clauses'] as $delta => $item){
			if($item == 'node.changed <= %s'){
				$unixtime = $query->where[0]['args'][$delta];
				$date_string = date('Y', $unixtime).'-'.date('m', $unixtime).'-'.date('d', $unixtime). ' 23:59:59';
				$date = date_create_from_format('Y-m-d H:i:s', $date_string);
				$query->where[0]['args'][$delta] = date_format($date, 'U');
			}
		}
	}
}
