<?php
// $Id$

/**
 * @file
 * This is the file description for Sms Sendega module.
 *
 * In this more verbose, multi-line description, you can specify what this
 * file does exactly. Make sure to wrap your documentation in column 78 so
 * that the file can be displayed nicely in default-sized consoles.
 */
include_once('includes/sendega.inc');
include_once('includes/rest.inc');

/**
 * Implementation of hook_gateway_info().
 */
function sms_sendega_gateway_info() {
  return array(
    'sendega' => array(
      'name' => 'Sendega',
      'configure form' => 'sms_sendega_admin_form',
      'send' => 'sms_sendega_send',
      'send form' => 'sms_sendega_send_form',
			'format number' => 'sms_sendega_format_number',
			'validate number' => 'sms_sendega_validate_number',
    ),
  );
}

function sms_sendega_admin_form($configuration) {
	
  $form['sms_sendega_ssl'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use SSL Encyption'),
    '#description' => t('Drupal\'s built-in HTTP client only supports SSL on PHP 4.3 compiled with OpenSSL.'),
    '#default_value' => $configuration['sms_sendega_ssl'],
  );

  $form['sms_sendega_cid'] = array(
    '#type' => 'textfield',
    '#title' => t('CID'),
    '#description' => t('Sendega customer ID.'),
    '#size' => 40,
    '#maxlength' => 255,
		'#required' => true,
    '#default_value' => $configuration['sms_sendega_cid'],
  );

  $form['sms_sendega_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#description' => t('The current password on your Sendega account.'),
    '#size' => 30,
    '#maxlength' => 64,
		'#required' => true,
    '#default_value' => $configuration['sms_sendega_password'],
  );
  
  return $form;
}

/**
 * Validates the submission of the configuration form.
 */ 
function sms_sendega_admin_form_validate($form, &$form_state) {

}

function sms_sendega_format_number ($number, $options = array()) {
	
}

function sms_sendega_validate_number (&$number, $options = array()) {
	if(substr($number, 0, 3) != '+47' || substr($number, 0, 2) != '47') {
		$number = '47'.$number;
	}
}

/**
 * Callback for sending messages.
 */
function sms_sendega_send($number, $message, $options) {
	$gateway = sms_gateways('gateway', 'sendega');
  $config = $gateway['configuration'];
	$schema = $config['sms_sendega_ssl'] ? 'https' : 'http';
	$sendega = new sendega($config['sms_sendega_cid'],$config['sms_sendega_password'], $schema);
	
	if ($log_only) {
		watchdog('sms_sendega', ('Send SMS number LOG ONLY: !number message: !message'), array('!number'=>$number, '!message'=>$message));
	} else {
		$sendega->sendSMS($number, $message, array('FromAlpha'=>variable_get('site_name', '')));
		if($sendega->success) {
			watchdog('sms_sendega', ('Sent SMS number: !number id: !id message: !message'), array('!number'=>$number, '!id'=>$sendega->result, '!message'=>$message));
		} else {
			watchdog('sms_sendega', ('SMS Error number: !number message: !message'), array('!number'=>$number, '!message'=>$sendega->result), WATCHDOG_ERROR);
		}
	}
	
	
	if (!$sendega->success) {
		return array('status'=>false, 'message'=>$sendega->result);
	} else {
		return array('status'=>true);
	}
}
