<?php

function kr_diverse_block($op = 'list', $delta = 0, $edit = array()) {

  if ($op == 'list') {
    $blocks[0] = array(
      'info' => 'KR: addthis widget', 
      'cache' => BLOCK_CACHE_PER_PAGE,
    );
    $blocks[1] = array(
      'info' => 'KR bildegalleri', 
      'cache' => BLOCK_CACHE_PER_PAGE,
    );
    return $blocks;
  }

  else if ($op == 'view') {
    switch ($delta) {
      case 0:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => '', 
          'content' => _kr_div_addthis(),
        );
        break;
      case 1:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => '', 
          'content' => _kr_bildegalleri(),
        );
        break;
    }
    return $block;
  }
}
function _kr_bildegalleri(){
  $nid = arg(1);
  $node_artikkel = node_load(array('nid' => $nid));
  if($node_artikkel->field_rel_bildegalleri[0]['nid']>1){
    $node = node_load(array('nid' => $node_artikkel->field_rel_bildegalleri[0]['nid']));
    dsm($node);
      drupal_add_js(drupal_get_path('theme', 'kr2011').'/flex/jquery.min.js');
      drupal_add_js(drupal_get_path('theme', 'kr2011').'/flex/jquery-noconflict.js');
      drupal_add_js(drupal_get_path('theme', 'kr2011').'/flex/jquery.flexslider.js', 'theme', 'header');
      drupal_add_js(drupal_get_path('theme', 'kr2011').'/flex/jquery.colorbox.js', 'theme', 'header');    
      drupal_add_css(drupal_get_path('theme', 'kr2011').'/flex/flexslider.css');
      drupal_add_css(drupal_get_path('theme', 'kr2011').'/flex/kr-flex.css');
      drupal_add_css(drupal_get_path('theme', 'kr2011').'/flex/colorbox.css');
      drupal_add_js('$(window).load(function() {
      jQuery164(".flexslider").flexslider({
        slideshow: "false",
      });
      jQuery164(".color'.$vars['nid'].'").colorbox({
      rel:"color", 
      transition:"fade",
      inline:true
      }); 
      
      });','inline');
      $hidden = '<div class="colorbox-images-container">';
      $html = '<div class="flexslider">
          <ul class="slides">';
      foreach ($node->field_galleri_bilde as $delta => $item) {
        $html .= '<li>';
        $html .= '<a class="color'.$vars['nid'].'" href="#bilde_'.$nid.'_'.$delta.'">';
        $html .= theme_imagecache('article_stor_slideshow', $node->field_galleri_bilde[$delta]['filepath']);
        if($node->field_galleri_desc[$delta]['value'] && $node->field_galleri_kredit[$delta]['value']){
          $html .= '<p>'.$node->field_galleri_desc[$delta]['value'];
          $html .= '<span class="kredit">'.$node->field_galleri_kredit[$delta]['value'].'</span></p>';
        }elseif($node->field_galleri_desc[$delta]['value']){
          $html .= '<p>'.$node->field_galleri_desc[$delta]['value'].'</p>';
        }elseif ($node->field_galleri_kredit[$delta]['value']) {
          $html .= '<p><span class="kredit">'.$node->field_galleri_kredit[$delta]['value'].'</span></p>';
        }
        $html .='</a>';
        $html .='</li>';
        $image = image_get_info(imagecache_create_path('slider_stort', $node->field_galleri_bilde[$delta]['filepath']));
  
        $hidden.= '<div id="bilde_'.$nid.'_'.$delta.'">
        '.theme_imagecache('slider_stort', $node->field_galleri_bilde[$delta]['filepath']).'
        <div class="caption" style="width: '.$image['width'].'px;">'.$node->field_galleri_desc[$delta]['value'].'</div>
        </div>';
      }
      $html .='</ul></div>';
      $hidden .='</div>';
      return $html. $hidden;
  }
}
function _kr_div_addthis(){
  if(arg(2) == 'edit' || arg(1) =='add'){
    return;
  }
  $node=node_load(arg(1));
  $addthis_link_title=$node->title;
  return theme('op_addthis_widget', $addthis_link_title);
}
function kr_div_forside_clear($form_id, $form_values){

  dmemcache_flush();
  db_query("DELETE FROM {views_content_cache}");
  db_query("DELETE FROM {cache_views}");
  db_query("DELETE FROM {cache_views_data}");
  db_query("DELETE FROM {cache_page}");
  cache_clear_all();
}
function kr_diverse_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'draggableviews_view_draggabletable_form_articles_page_2'){
    $form['#submit'][] = 'kr_div_forside_clear';
  }
  if($form_id == 'article_node_form' && arg(1)=='add'){
    
    global $user;
    $query = db_query('SELECT nr.title, n.nid FROM {content_type_author} ca
    LEFT JOIN {node} n ON ca.nid=n.nid
    LEFT JOIN {node_revisions} nr ON nr.vid=n.vid
    WHERE ca.field_author_user_uid LIKE %d',$user->uid);
    $result = db_fetch_object($query);

 // drupal_set_message($form_id.' '.$result->title);
    if($result->nid>0){
      $js='
      Drupal.behaviors.kr_div = function (context) {
        $("#edit-field-op-author-0-nid-nid").val("'.$result->title.' [nid:'.$result->nid.']");
      };
      ';
  //drupal_set_message($js);
      drupal_add_js($js, 'inline');
    }
  }

  //$("#edit-field-op-author-0-nid-nid").value(22);
}
function kr_diverse_nodeapi(&$node, $op, $teaser, $page) {
  switch ($op) {
    case 'insert':
    case 'update':
    case 'delete':
    case 'delete revision':
      //views_content_cache_update_set($node, 'node');
      if(function_exists('expire_cache_derivative')){
        $paths['front'] = '<front>';
        expire_cache_derivative($paths);
      }
      
      break;
  }
  if($op == 'view' && $node->type =='job'){
    $node->title = str_replace('_', '',$node->title);  
    $node->content['#title'] = str_replace('_', '',$node->title);  
    drupal_set_title(str_replace('_', '',$node->title));
  }
}

/**
 * Implementation of hook_twitter_pull_blocks()
 */
function kr_diverse_twitter_pull_blocks() {
  $block->delta = 'kr_tweets';
  $block->name = t('KR Tweets');
  $block->title = t('Kommunevalg på Twitter');
  $block->tweetkey = 'kommunevalg';
  $block->number_of_items = 7;
//  $block->theme_key = 'kr_tweets';
  return array($block->delta => $block);
}