<?php

function copy_front_page_to_new_theme(){
	db_query('DELETE FROM {draggableviews_structure} WHERE view_name = "forside"');
	db_query('INSERT INTO {draggableviews_structure} ( view_name, nid, delta, args, value )
SELECT  \'forside\', d.nid, d.delta, d.args, d.value
FROM    draggableviews_structure d
WHERE   d.view_name = \'articles\'');
}

function kr_diverse_block($op = 'list', $delta = 0, $edit = array()) {

  if ($op == 'list') {
    $blocks[0] = array(
      'info' => 'KR: addthis widget', 
      'cache' => BLOCK_CACHE_PER_PAGE,
    );
    $blocks[1] = array(
      'info' => 'KR bildegalleri', 
      'cache' => BLOCK_CACHE_PER_PAGE,
    );
    $blocks[2] = array(
      'info' => 'KR breaking', 
      'cache' => BLOCK_CACHE_PER_PAGE,
    );
    $blocks[3] = array(
      'info' => 'Admin lenker', 
      'cache' => BLOCK_CACHE_PER_ROLE,
    );
    return $blocks;
  }

  else if ($op == 'view') {
    switch ($delta) {
      case 0:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => '', 
          'content' => _kr_div_addthis(),
        );
        break;
      case 1:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => '', 
          'content' => _kr_bildegalleriet(),
        );
        break;
      case 2:
        // Your module will need to define this function to render the block.
        $html = _kr_aktuelle();
		if(strlen($html)>0){
	        drupal_add_js(drupal_get_path('module', 'kr_diverse') . '/kr_div.js');
			drupal_add_js('(function ($) {
				$(document).ready(function() {
					
				});
			}(jQuery));', 'inline');
		}
        $block = array(
          'subject' => '', 
          'content' => $html,
        );
        break;
	  case 3:
	  	$block = array(
	  		'subject' => '',
	  		'content' => _kr_div_admin_links()
		);
		  break;
    }
    return $block;
  }
  else if ($op == 'configure' && $delta == 2) {
  	$terms = taxonomy_get_tree(43);
	$options[0] = 'Ingen valgt';
	foreach($terms as $delta => $term){
		$options[$term->tid] = $term->name;
	}
  	$form['tax'] = array(
		'#type' => 'select', 	
  		'#title' => t('Choose category'), 	
  		'#default_value' => variable_get('kr_diverse_aktuell_tax', 10),
		'#options' => $options,   		
	);
	$form['number'] = array(
		'#type' => 'textfield',
		'#title' => t('Number of items shown'),
		'#default_value' => variable_get('kr_diverse_aktuell_number', 10)
	);
  	return $form;
  }
  else if ($op == 'save' && $delta == 2) {
    variable_set('kr_diverse_aktuell_tax', $edit['tax']);
    variable_set('kr_diverse_aktuell_number', $edit['number']);
  }
}
function _kr_div_admin_links(){
	global $user;
	$title = '';
	$type = 'ul';
	$attributes = array('class' => 'adminliste');
	$items = array();
	if(in_array('editor', $user->roles) || in_array('web editor', $user->roles) || in_array('administrator', $user->roles)){
		$items[] = l('Rediger forside', 'redigerforside');
	}
	if(user_access('administer block')){
		$items[] = l('Endre "breaking" liste', 'admin/build/block/configure/kr_diverse/2');
	}
	if(count($items)>0){
		return theme('item_list', $items, $title, $type, $attributes);;
	}else{
		return '';
	}
}
function _kr_aktuelle(){
	$tax = variable_get('kr_diverse_aktuell_tax', 0);
	$number = variable_get('kr_diverse_aktuell_number', 10);
	if(!is_numeric($number)){
		$number = 10;
	}

	if($tax == 0){
		return;
	}else{
		$query = db_query('SELECT * FROM term_node t
		LEFT JOIN node n ON t.vid = n.vid
		WHERE t.tid = '.$tax.' AND n.status = 1
		ORDER BY n.created DESC
		LIMIT '.$number);
		$taxonomy = taxonomy_get_term($tax);
		
		while($result = db_fetch_object($query)){
			$lis .= '<li><a href="'.url('node/'.$result->nid).'">'.$result->title.'</a></li>';
		}
		$html = '
		<div class="ticker">
			<div class="ticker-label">'.l($taxonomy->name.':', 'taxonomy/term/'.$taxonomy->tid).'</div>
			<div class="ticker-news">
				<ul>
					'.$lis.'
				</ul>
			</div>
			<div class="ticker-controls">
				<div class="ticker-prev"><span></span></div>				
				<div class="ticker-next"><span></span></div>
			</div>
		</div>';
		return $html;
	}	
}
function _kr_bildegalleriet(){
  $nid = arg(1);
  $node_artikkel = node_load(array('nid' => $nid));
  if($node_artikkel->field_rel_bildegalleri[0]['nid']>1){
    $node = node_load(array('nid' => $node_artikkel->field_rel_bildegalleri[0]['nid']));
    if($node->status == 1){
      drupal_add_js(drupal_get_path('theme', 'kr2011').'/flex/jquery.min.js');
      drupal_add_js(drupal_get_path('theme', 'kr2011').'/flex/jquery-noconflict.js');
      drupal_add_js(drupal_get_path('theme', 'kr2011').'/flex/jquery.flexslider.js', 'theme', 'header');
      drupal_add_js(drupal_get_path('theme', 'kr2011').'/flex/jquery.colorbox.js', 'theme', 'header');    
      drupal_add_css(drupal_get_path('theme', 'kr2011').'/flex/flexslider.css');
      drupal_add_css(drupal_get_path('theme', 'kr2011').'/flex/kr-flex.css');
      drupal_add_css(drupal_get_path('theme', 'kr2011').'/flex/colorbox.css');
      drupal_add_js('
      jQuery164(window).load(function() {
        jQuery164(".flexslider").flexslider({
          slideshow: "false"
        });
        jQuery164(".color'.$vars['nid'].'").colorbox({
          rel:"color", 
          transition:"fade",
          inline:true,
          width:"75%", 
          height:"75%"
        }); 
        
        jQuery164(document).bind("cbox_complete", function(){
          max_width = jQuery164("#cboxLoadedContent").width();
          max_width = max_width - 20;
          max_height = jQuery164("#cboxLoadedContent").height();
          max_height = max_height - jQuery164("#cboxLoadedContent .cimage .caption").height() - 20;
          
          jQuery164("#cboxLoadedContent .cimage img").attr("width", max_width+"px");
          jQuery164("#cboxLoadedContent .cimage img").attr("height", "");
          jQuery164("#cboxLoadedContent .cimage .caption").width(max_width+"px");
          
          if(jQuery164("#cboxLoadedContent .cimage img").height()>max_height){
            jQuery164("#cboxLoadedContent .cimage img").attr("width", "");
            jQuery164("#cboxLoadedContent .cimage img").attr("height", max_height+"px");
          }
        
      });
      
      });','inline');
      $hidden = '<div class="colorbox-images-container">';
      $html = '<div class="flexslider">
          <ul class="slides">';
      foreach ($node->field_galleri_bilde as $delta => $item) {
        $html .= '<li>';
        $html .= '<a class="color'.$vars['nid'].'" href="#bilde_'.$nid.'_'.$delta.'">';
        $html .= theme_imagecache('article_stor_slideshow', $node->field_galleri_bilde[$delta]['filepath']);
        if($node->field_galleri_desc[$delta]['value'] && $node->field_galleri_kredit[$delta]['value']){
          $html .= '<p>'.$node->field_galleri_desc[$delta]['value'];
          $html .= '<span class="kredit">'.$node->field_galleri_kredit[$delta]['value'].'</span></p>';
        }elseif($node->field_galleri_desc[$delta]['value']){
          $html .= '<p>'.$node->field_galleri_desc[$delta]['value'].'</p>';
        }elseif ($node->field_galleri_kredit[$delta]['value']) {
          $html .= '<p><span class="kredit">'.$node->field_galleri_kredit[$delta]['value'].'</span></p>';
        }
        $html .='</a>';
        $html .='</li>';
        $image = image_get_info(imagecache_create_path('slider_stort', $node->field_galleri_bilde[$delta]['filepath']));
  //<img src="'.imagecache_create_path('slider_stort', $node->field_galleri_bilde[$delta]['filepath']).'">
        $hidden.= '<div id="bilde_'.$nid.'_'.$delta.'" class="cimage">
        '.theme_imagecache('slider_stort', $node->field_galleri_bilde[$delta]['filepath']).'
        <div class="caption" style="width: '.$image['width'].'px;">'.$node->field_galleri_desc[$delta]['value'].'</div>
        </div>';
      }
      $html .='</ul></div>';
      $hidden .='</div>';
      return $html. $hidden;
    }
  }
}
function _kr_div_addthis(){
  return '<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style ">
<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
<a class="addthis_button_tweet"></a>
<a class="addthis_counter addthis_pill_style"></a>
</div>
<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ramsalt"></script>
<!-- AddThis Button END -->';	
	
	
  if(arg(2) == 'edit' || arg(1) =='add'){
    return;
  }
  $node=node_load(arg(1));
  $addthis_link_title=$node->title;
  return theme('op_addthis_widget', $addthis_link_title);
}
function kr_div_forside_clear($form_id, $form_values){

  dmemcache_flush();
  db_query("DELETE FROM {views_content_cache}");
  db_query("DELETE FROM {cache_views}");
  db_query("DELETE FROM {cache_views_data}");
  db_query("DELETE FROM {cache_page}");
  cache_clear_all();
}
function kr_diverse_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'draggableviews_view_draggabletable_form_articles_page_2'){
    $form['#submit'][] = 'kr_div_forside_clear';
  }
  if($form_id == 'article_node_form' && arg(1)=='add'){
    
    global $user;
    $query = db_query('SELECT nr.title, n.nid FROM {content_type_author} ca
    LEFT JOIN {node} n ON ca.nid=n.nid
    LEFT JOIN {node_revisions} nr ON nr.vid=n.vid
    WHERE ca.field_author_user_uid LIKE %d',$user->uid);
    $result = db_fetch_object($query);

 // drupal_set_message($form_id.' '.$result->title);
    if($result->nid>0){
      $js='
      Drupal.behaviors.kr_div = function (context) {
        $("#edit-field-op-author-0-nid-nid").val("'.$result->title.' [nid:'.$result->nid.']");
      };
      ';
  //drupal_set_message($js);
      drupal_add_js($js, 'inline');
    }
  }

	if($form_id == 'user_login'){
		$form['#attributes']['class'] = 'form-label-alter';
	}

  //$("#edit-field-op-author-0-nid-nid").value(22);
}
function kr_diverse_nodeapi(&$node, $op, $teaser, $page) {
  switch ($op) {
    case 'insert':
    case 'update':
    case 'delete':
    case 'delete revision':
      //views_content_cache_update_set($node, 'node');
      if(function_exists('expire_cache_derivative')){
        $paths['front'] = '<front>';
        expire_cache_derivative($paths);
      }
      
      break;
  }
  if($op == 'view' && $node->type =='job'){
    $node->title = str_replace('_', '',$node->title);  
    $node->content['#title'] = str_replace('_', '',$node->title);  
    drupal_set_title(str_replace('_', '',$node->title));
  }
}

/**
 * Implementation of hook_twitter_pull_blocks()
 */
function kr_diverse_twitter_pull_blocks() {
  $block->delta = 'kr_tweets';
  $block->name = t('KR Tweets');
  $block->title = t('Kommunevalg på Twitter');
  $block->tweetkey = 'kommunevalg';
  $block->number_of_items = 7;
//  $block->theme_key = 'kr_tweets';
  return array($block->delta => $block);
}

function kr_diverse_apachesolr_query_prepare($query){
	global $user;
	if($user->uid == 1){
		dsm($query);
	}
	$query->setSolrsort('ds_created', 'desc');
	//$query->operator = 'AND';
}
function kr_diverse_apachesolr_query_alter($query) {
	global $user;
	if($user->uid == 1){
		dsm(array($query, $query->getParams(), $query->getSolrParams()));
	}
	$query->addParam('mm', 1);
	$query->params['mm'] = '1';
}
