<?php

function kr_wordcount_form_alter(&$form, &$form_state, $form_id){
  $add=false;
  if($form['title']['#type'] == 'textfield'){
    $js='$("#edit-title").jqEasyCounter({
      "maxChars": 255,
      "maxCharsWarning": 70
    });';
    $add=true;
  }
  if($add){
    $js_all='
    Drupal.behaviors.run_after_page_loads = function (context) {
    // Some jQuery that runs once the page loads.
      '.$js.'
    }';
    drupal_add_js(drupal_get_path('module', 'kr_wordcount') . '/jquery.jqEasyCharCounter.js');
    drupal_add_js($js_all, 'inline');
  }

  
}
