<?php
// $Id: google_charts.module,v 1.16.4.2 2010/07/02 01:04:23 brmassa Exp $
/**
 * @author Bruno Massa http://drupal.org/user/67164
 * @file
 * Use Google Charts on your site.
 *
 * @note only hooks are here.
 */

/**
 * Implementation of hook_charts_info().
 *
 * Its a Charts module hook. It defines almost all aspects
 * of a chart provider, like its name, what types of charts
 * it can perform and what are the restrictions.
 */
function jqplot_charts_charts_info() {
  return array(
    'jqplot' => array(
      'file'    => drupal_get_path('module', 'jqplot_charts') .'/jqplot_charts.inc',
      'name'    => t('jqPlot Chart'),
      'render'  => '_jqplot_charts_render',
      'types'   => array('line2D', 'vbar2D', 'hbar2D'),
    ),
  );
}

function jqplot_charts_set_charts ($id = null, $data = null, $settings = null) {
  static $charts = array();
  
  if($id && $data && $settings) {
    if (!isset($charts[$id])) {
      $charts[$id]['id'] = $id;
      $charts[$id]['data'] = $data;
      $charts[$id]['settings'] = $settings;
    }
  }
  return $charts;
}

function jqplot_charts_preprocess_page(&$vars) {
  $charts = jqplot_charts_set_charts();

  $chart_loader = '';
  foreach($charts as $id => $chart) {
    $chart_loader .= '$.jqplot("'.$chart['id'].'", '.json_encode($chart['data']).',
     '.$chart['settings'].'); '; 
  }

  drupal_add_js('(function ($) { try { Drupal.behaviors.jqplotCharts = function(context) {
  	'.$chart_loader.'	 
  	}; } catch(err) { } 
  })(jQuery);', 
  'inline');
}

/**
 * Implementation of hook_chart_types().
 */
/*
 function google_charts_chart_types() {
  return array(
    'venn'    => t('Venn'),
    'scatter' => t('Scatter Plot'),
    'hbar2Ds' => t('Horizontal Bar Stacked 2D'),
    'vbar2Ds' => t('Vertical Bar Stacked 2D'),
  );
}
*/