<?php

/**
 * Implements hook_init().
 */
function pollanon_init() {
  drupal_add_css(drupal_get_path('module', 'pollanon') .'/pollanon.css');
  drupal_add_js(drupal_get_path('module', 'pollanon') .'/js/jquery.cookie.min.js');
  drupal_add_js(drupal_get_path('module', 'pollanon') .'/js/pollanon.pack.js');
}


/**
 * Implementation of hook_menu().
 */
function pollanon_menu() {
  $items = array();
  $items['admin/settings/pollanon'] = array(
    'title' => t('Poll Enhancements'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pollanon_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'pollanon.admin.inc',
  );
  $items['pollanon/ajax/vote'] = array(
    'title' => '',
    'type' => MENU_CALLBACK,
    'page callback' => '_pollanon_ajax_vote',
    'access arguments' => array('vote on polls'),
  );
  return $items;
}


/**
 * Implements hook_form_alter().
 */
function pollanon_form_alter(&$form, $form_state, $form_id) {
  static $settings_initialized = FALSE;

  if ($form_id == 'poll_view_voting' && user_is_anonymous()) {
    $node = $form['#node'];

    if (empty($form['#attributes']['class'])) {
      $form['#attributes']['class'] = 'pollanon';
    }
    else {
      $form['#attributes']['class'] .= ' pollanon';
    }

    $results = _pollanon_poll_results($node->nid);
    $form['pollanon-poll-results'] = array(
        '#value' => '<div class="pollanon-poll-results hidden" data-nid="' . $node->nid .  '">' . $results . '</div>'
    );
    $form['pollanonkey'] = array(
        '#type' => 'hidden',
        '#default_value' => ''
    );
    $form['pollanon-nid'] = array(
        '#type' => 'hidden',
        '#default_value' => $node->nid
    );
    
    $form['vote']['#validate'][] = 'pollanon_handle_vote_validate';
    $form['vote']['#submit'][] = 'pollanon_handle_vote_submit';

    if (variable_get('pollanon_use_ajah', FALSE)) {
      $form['vote']['#ahah'] = array(
        'path' => 'pollanon/ajax/vote',
        'wrapper' => 'poll-view-voting', //id attribute of the wrapper element => works only with one poll on the page at the time
        'method' => 'replace',
        'effect' => 'fade',
      );
    }

    if (!$settings_initialized) {
       $js = <<<EOT
              if (typeof PollAnon == 'undefined') {
                var PollAnon = {};
              }
              PollAnon.nid = {$node->nid};
EOT;
       $form['pollanon_js'] = array(
           '#value' => "<script type='text/javascript'>\n $js \n</script>",
       );
    }
  }
}


function pollanon_handle_vote_validate($form, &$form_state) {
  if (!variable_get('pollanon_use_cookie_method', TRUE) ||  //Cookie restrictions disabled?
      empty($form_state['values']['pollanonkey']) ||        //Pollanon key not found
      user_is_logged_in()) {                                //Authenticated users are handled by the poll module
          return;
  }

  if (!_pollanon_validate_request($form_state['values']['pollanonkey'])) {
    _pollanon_cookiemessage(t('Cookie support required to anonymous voting'));
    drupal_goto($_GET['q']);
  }
  if (!_pollanon_ip_check($form['#node']->nid, ip_address())) {
    _pollanon_cookiemessage(t('Voting temporarily closed for your remote address.'));
    drupal_goto($_GET['q']);
  }
}


function pollanon_handle_vote_submit($form, &$form_state) {
  global $user;

  if (!variable_get('pollanon_use_cookie_method', TRUE) ||  //Cookie restrictions disabled?
      empty($form_state['values']['pollanonkey']) ||        //Pollanon key not found
      user_is_logged_in() ||                                //Authenticated users are handled by the poll module
      !isset($form['#node'])) {
          return;
  }

  $pollanon_key = $form_state['values']['pollanonkey'];
  $ip_address   = ip_address();
  $node         = $form['#node'];
  $choice       = $form_state['values']['choice'];

  //Create distinctive string to replace the real IP address
  $fake_ip_value = "$ip_address#$pollanon_key";

  _pollanon_modify_poll_vote_record($node->nid, $fake_ip_value, $ip_address);
  _pollanon_clear_session_messages();

  $cookie_name = 'pa-' . $node->nid;
  //Set flag: User has submitted this form
  setcookie($cookie_name, '1', time()+3600*24*31, '/'); // Expire in 3 months
  //Remove the key cookie
  setcookie('pa-submit', '', time() - 99999, '/');
}

/*
 * $return string Four letter string from the beginning of the pollanon key.
 */
function _pollanon_build_key() {
  $user_agent   = $_SERVER['HTTP_USER_AGENT'];
  $user_agent_i = floor(strlen($user_agent)/2);
  $pollanon_key = !empty($user_agent)? substr($user_agent, $user_agent_i, 2) . strlen($user_agent) : '';
  return $pollanon_key;
}

/*
 * Sanitize possible automated attempts to abuse the form.
 * @return boolean Whether the form posted key value matches builded key.
 */
function _pollanon_validate_request($posted_key_value) {
  $builded_key = _pollanon_build_key();
  $posted_key_parts = explode('-', $posted_key_value);
  $cookie_value = isset($_COOKIE['pa-submit'])? $_COOKIE['pa-submit'] : '';
  $cookie_key_parts = explode('-', $_COOKIE['pa-submit']);
  $js_generated_time = time(round($posted_key_parts[1]/1000));
  return ($builded_key == $cookie_key_parts[0] &&
          $builded_key == $posted_key_parts[0] &&
          $js_generated_time > time() - 600);
}


function _pollanon_modify_poll_vote_record($nid, $fake_ip_value, $ip_address) {
  db_query("UPDATE {poll_votes} SET hostname = '%s' WHERE nid = %d AND hostname = '%s'", $fake_ip_value, $nid, $ip_address);
}

/*
function _pollanon_remove_poll_vote_record($nid, $ip_address, $choice) {
  db_query("DELETE FROM {poll_votes} WHERE nid = %d AND hostname = '%s'", $nid, $ip_address);
  db_query("UPDATE {poll_choices} SET chvotes = chvotes - 1 WHERE nid = %d AND chorder = %d", $nid, $choice);
}
*/

function _pollanon_poll_results($nid) {
  $node = node_load($nid);
  if ($node && $node->type == 'poll') {
    return poll_view_results($node, FALSE, FALSE, FALSE);
  }
  else {
    return FALSE;
  }
}


function _pollanon_clear_session_messages() {
  $msgs = drupal_get_messages('status');
  if (count($msgs['status']) == 1 && $msgs['status'][0] == t('Your vote was recorded.')) {
    drupal_get_messages('status', TRUE); //Clear status messages queue
    _pollanon_cookiemessage(t('Your vote was recorded.'));
  }
  if (count($_SESSION) == 1 && isset($_SESSION['messages']) && empty($_SESSION['messages'])) {
    //Messages without any content => clear
    unset($_SESSION);
  }
}

function _pollanon_ip_check($nid, $ip_address) {
  $ok = FALSE;

  if (variable_get('pollanon_threshold_count', 10) == 0) {
    return TRUE; //No IP restrictions
  }

  $votes_for_this_ip = db_result(db_query("SELECT COUNT(*) FROM {pollanon_votes} " .
                          "WHERE nid = %d AND hostname = '%s' AND timestamp > %d",
                          $nid, $ip_address, time() - variable_get('pollanon_threshold_time', 600)));

  //Is the given IP address allowed vote once more?
  if ($votes_for_this_ip < variable_get('pollanon_threshold_count', 10)) {
    db_query("INSERT INTO {pollanon_votes} (nid, hostname, timestamp) ".
              "VALUES (%d, '%s', %d)", $nid, $ip_address, time());
    $ok = TRUE;
  }
  return $ok;
}

function pollanon_cron() {
  db_query("DELETE FROM {pollanon_votes} WHERE timestamp < %d", time() - variable_get('pollanon_threshold_time', 600));
}

function _pollanon_cookiemessage($msg) {
  static $cache = '';
  if (!empty($msg)) {
    $cache .= "$msg ";
    setcookie('pa-messages', check_plain($cache), 0, '/');
  }
  return $cache;
}


function _pollanon_ajax_vote() {
  if (!isset($_POST['pollanon-nid'])) {
    drupal_json(array('status' => TRUE, 'data' => ''));
    exit();
  }

  /* Execute form programmatically */
  $form_state = array('storage' => NULL, 'submitted' => FALSE);
  $form_build_id = $_POST['form_build_id'];

// Get the form from the cache.
  $form = form_get_cache($form_build_id, $form_state);
  $args = $form['#parameters'];
  $form_id = array_shift($args);

  // We will run some of the submit handlers so we need to disable redirecting.
  $form['#redirect'] = FALSE;

  // We need to process the form, prepare for that by setting a few internals
  // variables.
  $form['#post'] = $_POST;
  $form['#programmed'] = FALSE;
  $form_state['post'] = $_POST;

// Build, validate and if possible, submit the form.
  drupal_process_form($form_id, $form, $form_state);
  // This call recreates the form relying solely on the form_state that the
  // drupal_process_form set up.
  $form = drupal_rebuild_form($form_id, $form_state, $args, $form_build_id);

  // Render the new output.
  $output = drupal_render($form);
  if (!$output) {
    $output = _pollanon_cookiemessage(NULL);
  }
  drupal_json(array('status' => TRUE, 'data' => $output));
}
